-- ============================================
-- xmake.lua template for STM32
-- Generated by Xbuild MCU extension
-- ============================================
--
-- Architecture (keep this file generic):
--
--   xmake.lua              build engine. Knows no project-specific names.
--   .lua/config.json       settings shared by every target.
--   .lua/targets/*.json    one file per build target (board/variant/role),
--                          overriding or extending the shared settings.
--   .lua/tasks/*.lua       tasks (flash/docs/... plus any project-authored ones).
--
-- Target identity: the xmake target ID is the *file-name stem* of the target
-- JSON (example.json -> "example", addressed as `xmake build example`). The
-- optional "name" field inside the JSON only names the artifact
-- (example-project.elf). Passing the artifact name to xmake is a silent
-- no-op: `xmake build example-project` reports success and produces nothing.
-- Always address targets by stem.
--
-- A project without .lua/targets/ keeps working as a single "firmware" target
-- built from .lua/config.json alone (back-compat with single-image projects).

set_config("plat", "cross")
set_config("arch", "arm")

includes(".lua/tasks/*.lua")

-- ========================================
-- GCC FPU flags based on the cortex-m core
-- ========================================
local fpu_table = {
    -- Cores without FPU (Ignore user's choice, always -mfloat-abi=soft)
    ["cortex-m0"]     = { cxflags = {"-mfloat-abi=soft"}, ldflags = {"-mfloat-abi=soft"}, asflags = {} },
    ["cortex-m0plus"] = { cxflags = {"-mfloat-abi=soft"}, ldflags = {"-mfloat-abi=soft"}, asflags = {} },
    ["cortex-m3"]     = { cxflags = {"-mfloat-abi=soft"}, ldflags = {"-mfloat-abi=soft"}, asflags = {} },
    ["cortex-m23"]    = { cxflags = {"-mfloat-abi=soft"}, ldflags = {"-mfloat-abi=soft"}, asflags = {} },

    -- Cores with Single-Precision FPU
    ["cortex-m4"]     = { cxflags = {"-mfpu=auto", "-mfloat-abi=${abi}", "-fsingle-precision-constant"}, ldflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, asflags = {"-mfpu=auto"} },
    ["cortex-m33"]    = { cxflags = {"-mfpu=auto", "-mfloat-abi=${abi}", "-fsingle-precision-constant"}, ldflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, asflags = {"-mfpu=auto"} },

    -- Cores with Double-Precision FPU
    ["cortex-m7"]     = { cxflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, ldflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, asflags = {"-mfpu=auto"} },
    ["cortex-m55"]    = { cxflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, ldflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, asflags = {"-mfpu=auto"} },
    ["cortex-m85"]    = { cxflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, ldflags = {"-mfpu=auto", "-mfloat-abi=${abi}"}, asflags = {"-mfpu=auto"} }
}

-- ========================================
-- Optimization presets configuration
-- Based on GCC optimization levels
-- ========================================
local optimization_presets = {
    ["debug"] = {
        opt_flag = "-O0", debug_level = 3, lto = false,
        description = "No optimization, full debug info"
    },
    ["debug-optimized"] = {
        opt_flag = "-Og", debug_level = 3, lto = false,
        description = "Optimized for debugging"
    },
    ["balanced"] = {
        opt_flag = "-O1", debug_level = 2, lto = false,
        description = "Basic optimization"
    },
    ["release"] = {
        opt_flag = "-Os", debug_level = 1, lto = false,
        description = "Optimized for size"
    },
    ["speed"] = {
        opt_flag = "-O2", debug_level = 1, lto = false,
        description = "Optimized for speed"
    },
    ["speed-max"] = {
        opt_flag = "-O3", debug_level = 0, lto = false,
        description = "Maximum speed optimization"
    },
    ["size-max"] = {
        opt_flag = "-Oz", debug_level = 0, lto = false,
        description = "Maximum size optimization"
    },
    ["release-lto"] = {
        opt_flag = "-Os", debug_level = 1, lto = true,
        description = "Size optimization with LTO"
    }
}

-- ========================================
-- Get optimization flags for current mode
-- ========================================
local function get_optimization_flags(target)
    local mode = get_config("mode") or "debug"

    local optimization = target:data("optimization") or {}

    local preset_id = optimization[mode] or mode
    local preset = optimization_presets[preset_id] or optimization_presets["debug"]

    local opt_flag   = preset.opt_flag
    local debug_flag = "-g" .. tostring(preset.debug_level)
    local lto_flag   = preset.lto and "-flto" or nil

    return opt_flag, debug_flag, lto_flag
end

-- ========================================
-- Toolchain
-- ========================================
toolchain("stm32-gcc")
    on_load(function (toolchain)
        import("core.base.json")

        toolchain:set("kind", "standalone")
        toolchain:set("sdkdir", json.decode(io.readfile(".lua/config.json")).arm_gcc_path)
        toolchain:set("toolset", "cc", "arm-none-eabi-gcc")
        toolchain:set("toolset", "cxx", "arm-none-eabi-g++")
        toolchain:set("toolset", "ld", "arm-none-eabi-g++")
        toolchain:set("toolset", "as", "arm-none-eabi-gcc")
        toolchain:set("toolset", "ar", "arm-none-eabi-ar")
        toolchain:set("toolset", "objcopy", "arm-none-eabi-objcopy")
        toolchain:set("toolset", "size", "arm-none-eabi-size")
    end)

    on_check(function (toolchain)
        return true
    end)
toolchain_end()

-- ========================================
-- Build modes
-- ========================================
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})

-- ========================================
-- Firmware targets
-- ========================================
-- One target per JSON file in .lua/targets/ .
-- The file-name stem is the target ID; the artifact name and the per-target
-- settings are read from that JSON inside on_load, where the script-scope APIs
-- (import/json/io) are available. Adding or removing a board means adding or
-- removing one file - this script does not change.
--
-- With no target files at all the project degrades to a single "firmware" target
-- driven by .lua/config.json alone, so single-image projects (and projects created
-- before multi-target support) keep building without edits.
--
-- Note: raise()/error()/assert() are not defined at this scope (only inside target
-- callbacks), so the empty case is handled by falling back rather than by raising.
local specs = {}
local specfiles = os.files(".lua/targets/*.json")
if #specfiles == 0 then
    table.insert(specs, { stem = "firmware" })
else
    for _, specfile in ipairs(specfiles) do
        local stem = specfile:match("([^/\\]+)%.json$") or specfile
        table.insert(specs, { stem = stem, path = specfile })
    end
end

for _, spec_entry in ipairs(specs) do
    local stem     = spec_entry.stem
    local specpath = spec_entry.path

    target(stem)
        set_kind("binary")

        -- ========================================
        -- Loading the structure
        -- ========================================
        on_load(function (target)
            import("core.base.json")

            local config_path = ".lua/config.json"
            if not os.isfile(config_path) then
                raise(".lua/config.json not found! Run 'Xmake: Initialize Project' from the extension.")
            end

            local settings = json.decode(io.readfile(config_path))

            -- Per-target overlay. A missing file means the back-compat single
            -- "firmware" target: nothing overrides the shared settings.
            local spec = {}
            if specpath then
                spec = json.decode(io.readfile(specpath))

                -- Supported per-target fields. Scalar fields override the common
                -- project settings; list fields (defines/includedirs/sources)
                -- extend them. Unknown keys are reported instead of being silently
                -- ignored (so this script stays valid as the extension evolves).
                local supported = {
                    name = true, languages = true,
                    defines = true, includedirs = true, sources = true,
                    mcu_series = true, mcu_core = true, float_abi = true, mcu_device = true,
                    ld_script = true, svd_file = true, jlink_path = true,
                    optimization = true, postbuild = true,
                }

                for key, _ in pairs(spec) do
                    if not supported[key] then
                        cprint("${yellow}warning:${clear} %s: unknown key '%s' is ignored", specpath, key)
                    end
                end
            end

            -- An empty string counts as ABSENT. "" is truthy in Lua, and a config or
            -- overlay written by hand (or by a tool) may legitimately carry "". Without
            -- this, {"float_abi": ""} produced the single argument -mfloat-abi= and the
            -- build died with "missing argument"; {"mcu_series": ""} produced a bare -D.
            -- Tables are unaffected: "" == {} is false, so a table passes through.
            local function pick(key)
                local value = spec[key]
                if value == "" then
                    value = nil
                end
                if value == nil then
                    value = settings[key]
                end
                if value == "" then
                    value = nil
                end
                return value
            end

            -- Artifact name: the target's own "name", else the stem, else (in the
            -- back-compat case) the project name from config.json.
            --
            -- An empty string must be treated as absent: "" is TRUTHY in Lua, and the
            -- extension writes name = "" for a field the user never filled in. Without
            -- this the artifact is literally ".elf" (and the launch configuration
            -- points at a path ending in "/.elf").
            local spec_name = spec.name
            if type(spec_name) == "string" and spec_name == "" then
                spec_name = nil
            end

            local settings_name = settings.name
            if type(settings_name) == "string" and settings_name == "" then
                settings_name = nil
            end

            local artifact
            if spec_name then
                artifact = spec_name
            elseif specpath then
                artifact = stem
            else
                artifact = settings_name or stem
            end

            local mcu_series = pick("mcu_series")

            -- Both of these are read by on_config; leaving them nil makes Lua fail
            -- while building the flags (gsub/flag interpolation with nil), so they
            -- fall back to the values the pre-multi-target template hardcoded.
            --
            -- languages is resolved PER KEY rather than as one whole table: a partial
            -- overlay such as {"languages": {"c": "c99"}} must still inherit the shared
            -- C++ standard. Taking the table wholesale left languages["cpp"] nil, which
            -- reached target:set("languages", "c99", nil) without any error.
            -- The type guard makes a malformed value ("languages": "foo", which would
            -- otherwise be indexed as a string) fall back instead of raising.
            local shared_langs = settings.languages
            if type(shared_langs) ~= "table" then
                shared_langs = {}
            end

            local spec_langs = spec.languages
            if type(spec_langs) ~= "table" then
                spec_langs = {}
            end

            local function lang(key, fallback)
                local value = spec_langs[key]
                if value == nil or value == "" then
                    value = shared_langs[key]
                end
                if value == nil or value == "" then
                    value = fallback
                end
                return value
            end

            local languages = { c = lang("c", "c17"), cpp = lang("cpp", "c++20") }
            local float_abi = pick("float_abi") or "hard"

            target:set("languages",  languages["c"], languages["cpp"])
            target:set("filename",   artifact .. ".elf")
            target:set("toolchains", "stm32-gcc")
            target:set("warnings",   "all", "extra", "pedantic", "error=return-type")

            target:data_set("project_name", artifact)
            target:data_set("mcu_series",   mcu_series)
            target:data_set("mcu_core",     pick("mcu_core"))
            target:data_set("float_abi",    float_abi)
            target:data_set("mcu_device",   pick("mcu_device"))
            target:data_set("ld_script",    pick("ld_script"))
            target:data_set("jlink_path",   pick("jlink_path"))
            target:data_set("svd_file",     pick("svd_file"))
            target:data_set("optimization", pick("optimization"))

            -- Post-build command, kept raw here: the {bin}/{elf}/{target} tokens are
            -- resolved in after_build, where the real artifact paths are known (a
            -- path baked into config.json cannot be right for every build mode).
            target:data_set("postbuild", pick("postbuild") or nil)

            -- device selection macro (consumed by the CMSIS headers)
            target:add("defines", mcu_series)

            -- common project settings
            for _, def in ipairs(settings.defines or {}) do
                target:add("defines", def)
            end

            for _, dir in ipairs(settings.includedirs or {}) do
                target:add("includedirs", dir)
            end

            for _, file in ipairs(settings.sources or {}) do
                target:add("files", file)
            end

            -- per-target additions (board variant)
            for _, def in ipairs(spec.defines or {}) do
                target:add("defines", def)
            end

            for _, dir in ipairs(spec.includedirs or {}) do
                target:add("includedirs", dir)
            end

            for _, file in ipairs(spec.sources or {}) do
                target:add("files", file)
            end

            -- Optional clang-format settings from config.json: generate the
            -- .clang-format file and turn on format-on-save for C/C++.
            if settings.clang_format then
                local format_content = "# Generated automatically by Xmake from .lua/config.json\n---\n"
                for key, val in pairs(settings.clang_format) do
                    if type(val) == "string" then
                        format_content = format_content .. string.format("%s: '%s'\n", key, val)
                    else
                        format_content = format_content .. string.format("%s: %s\n", key, tostring(val))
                    end
                end

                io.writefile("./build/.clang-format", format_content, {check = true})

                local vscode_settings = table.concat({
                    "{",
                    "    \"editor.formatOnSave\": true,",
                    "    \"[c]\": {",
                    "        \"editor.defaultFormatter\": \"ms-vscode.cpptools\",",
                    "        \"editor.formatOnSave\": true",
                    "    },",
                    "    \"[cpp]\": {",
                    "        \"editor.defaultFormatter\": \"ms-vscode.cpptools\",",
                    "        \"editor.formatOnSave\": true",
                    "    }",
                    "}"
                }, "\n")
                os.mkdir(".vscode")
                io.writefile(".vscode/settings.json", vscode_settings, {check = true})
            end
        end)

        -- ========================================
        -- Compiler Configuration
        -- ========================================
        on_config(function (target)
            -- Every flag below derives from mcu_core. Without it Lua fails on
            -- string concatenation or nil:lower() with an unhelpful message, so it
            -- is validated first (raise() is available inside target callbacks).
            local mcu_core = target:data("mcu_core")
            if not mcu_core or mcu_core == "" then
                raise("mcu_core is not set - add it to .lua/config.json or to the target's .lua/targets/<name>.json")
            end

            -- The linker script is just as mandatory and is concatenated into "-T" a few
            -- lines below. Checked here so an unset value produces one actionable message
            -- instead of a bare "-T" from the linker or "attempt to concatenate a nil
            -- value" (which is what an empty string became once empty values started
            -- counting as absent).
            local ld_script = target:data("ld_script")
            if not ld_script or ld_script == "" then
                raise("ld_script is not set - add it to .lua/config.json or to the target's .lua/targets/<name>.json")
            end
            -- MCU flags
            target:add("cxflags", "-mcpu=".. mcu_core .." -mthumb", {force = true})
            target:add("asflags", "-mcpu=".. mcu_core .." -mthumb", {force = true})
            target:add("ldflags", "-mcpu=".. mcu_core .." -mthumb", {force = true})

            local core_flags = fpu_table[mcu_core:lower()]

            if not core_flags then
                raise("Unknown MCU core: " .. mcu_core .. ". Please update .lua/config.json or add a new mcu to the fpu_table in ./xmake.lua")
            end

            local abi = target:data("float_abi")
            local function apply_flags(flag_type, flags_list)
                for _, flag in ipairs(flags_list) do
                    local processed_flag = flag:gsub("%${abi}", abi)
                    target:add(flag_type, processed_flag, {force = true})
                end
            end

            apply_flags("cxflags", core_flags.cxflags)
            apply_flags("asflags", core_flags.asflags)
            apply_flags("ldflags", core_flags.ldflags)

            -- Optimisation (dynamic based on presets)
            local opt_flag, debug_flag, lto_flag = get_optimization_flags(target)
            target:add("cxflags", opt_flag, debug_flag, "-gdwarf-2")

            -- LTO support
            if lto_flag then
                target:add("cxflags", lto_flag)
                target:add("ldflags", lto_flag)
            end

            -- ========================================
            -- Compilation flags
            -- ========================================
            target:add("cxflags", "-Wall", "-Wextra", "-Werror=return-type")
            target:add("cxflags", "-ffunction-sections", "-fdata-sections")
            target:add("cxxflags", "-fno-exceptions", "-fno-rtti")

            -- ========================================
            -- Linker flags
            -- ========================================
            target:add("ldflags", "-T" .. target:data("ld_script"), {force = true})
            target:add("ldflags", "-specs=nano.specs", "-specs=nosys.specs", {force = true})
            target:add("ldflags", "-Wl,--gc-sections")

            local map_path = target:data("project_name") .. ".map"
            target:add("ldflags", "-Wl,-Map=" .. map_path, {force = true})
        end)

        -- ========================================
        -- Post-build: bin/hex + size + launch.json
        -- ========================================
        after_build(function (target)
            import("core.base.json")

            local targetfile = path.normalize(target:targetfile())
            local outdir     = path.normalize(path.directory(targetfile))
            local basename   = path.basename(targetfile)

            cprint("\r\n${rocket} ${green}Generating binary files${clear}")
            os.exec('arm-none-eabi-objcopy -O binary "%s" "%s/%s.bin"', targetfile, outdir, basename)   -- .bin
            os.exec('arm-none-eabi-objcopy -O ihex "%s" "%s/%s.hex"', targetfile, outdir, basename)     -- .hex
            os.exec('arm-none-eabi-size "%s"', targetfile)                                              -- size

            -- Post-build. The tokens are resolved against this build's real artifact
            -- paths, so one config.json string works for every mode and target:
            --   {target} artifact name without extension, as path.basename() returns it
            --   {bin}    absolute path of the generated .bin
            --   {elf}    absolute path of the built .elf
            local postbuild = target:data("postbuild")
            if postbuild then
                local bin_path = path.absolute(path.join(outdir, basename .. ".bin"))
                local elf_path = path.absolute(targetfile)
                postbuild = postbuild:gsub("{target}", function () return basename end)
                postbuild = postbuild:gsub("{bin}",    function () return bin_path end)
                postbuild = postbuild:gsub("{elf}",    function () return elf_path end)

                cprint("\r\n${gear} ${green}Postbuild run:${clear}")
                os.exec(postbuild)
            end

            -- Generate the Cortex Debug launch configuration. It is *merged* into
            -- .vscode/launch.json keyed by target, because after_build runs once per
            -- built target: overwriting the file would leave the debugger pointing at
            -- whichever target happened to build last.
            cprint("\r\n${hammer} ${green}Generating ${cyan}.vscode/launch.json${clear}")

            -- path.normalize("") returns NIL (measured on xmake 2.9.9 and 3.1.1), so it
            -- cannot be followed by :gsub: that crashed every project whose jlink_path
            -- was still empty - i.e. any project not yet fully configured - and made the
            -- JLinkGDBServerCL.exe fallback below unreachable.
            --
            -- Only the nil case is guarded. The decision itself is unchanged from 2.0.1:
            -- an actual JLink.exe path is rewritten in place, anything else collapses to
            -- the bare server name that cortex-debug resolves from PATH.
            local jlink_raw = target:data("jlink_path")
            local jlink_gdb = ""
            if type(jlink_raw) == "string" and jlink_raw ~= "" then
                jlink_gdb = path.normalize(jlink_raw) or ""
            end

            -- gsub returns (string, count); capture it in ONE value on its own statement.
            local jlink_gdb_norm = "JLinkGDBServerCL.exe"
            if jlink_gdb ~= "" then
                local substituted = jlink_gdb:gsub("[Jj][Ll][Ii][Nn][Kk]%.exe", "JLinkGDBServerCL.exe")
                if substituted ~= jlink_gdb then
                    -- Forward slashes, as 2.0.1 did: the value lands in JSON consumed by
                    -- cortex-debug, and a backslash would need escaping there.
                    jlink_gdb_norm = substituted:gsub("\\", "/")
                end
            end

            local relative_elf_path = path.relative(targetfile, os.projectdir()):gsub("\\", "/")
            local svd_file_norm     = (target:data("svd_file") or ""):gsub("\\", "/")

            local launch_dir  = ".vscode"
            local launch_path = path.join(launch_dir, "launch.json")

            -- Read the existing file first so unrelated debug configurations survive.
            -- A file that is not plain JSON (VS Code allows comments) is left
            -- untouched: silently replacing it would destroy the user's configs.
            local existing   = nil
            local parse_failed = false
            if os.isfile(launch_path) then
                try {
                    function ()
                        existing = json.decode(io.readfile(launch_path))
                    end,
                    catch {
                        function ()
                            parse_failed = true
                        end
                    }
                }
            end

            if parse_failed then
                cprint("${yellow}warning:${clear} .vscode/launch.json is not plain JSON "
                    .. "(comments are not supported) - left unchanged")
            else
                -- Only "configurations" is rebuilt. The rest of the document is kept
                -- as-is, because VS Code allows other top-level keys there ("inputs",
                -- "compounds") and reconstructing the file from scratch would silently
                -- delete them.
                local doc = (type(existing) == "table") and existing or {}
                local configs = (type(doc.configurations) == "table") and doc.configurations or {}

                -- The single-image project keeps the original configuration name so
                -- existing setups are not renamed on upgrade.
                local cfg_name = (stem == "firmware") and "JLink Debug" or ("JLink Debug (" .. stem .. ")")

                local kept = {}
                for _, cfg in ipairs(configs) do
                    if cfg.name ~= cfg_name then
                        table.insert(kept, cfg)
                    end
                end

                table.insert(kept, {
                    name               = cfg_name,
                    cwd                = "${workspaceFolder}",
                    executable         = "${workspaceFolder}/" .. relative_elf_path,
                    request            = "launch",
                    type               = "cortex-debug",
                    servertype         = "jlink",
                    serverpath         = jlink_gdb_norm,
                    device             = target:data("mcu_device"),
                    interface          = "swd",
                    svdFile            = "${workspaceFolder}/" .. svd_file_norm,
                    runToEntryPoint    = "main",
                    showDevDebugOutput = "raw"
                })

                doc.configurations = kept
                doc.version        = doc.version or "0.2.0"

                -- json.encode ignores the {indent} option, so the layout is assembled
                -- here: the flat top-level keys first, then one configuration per line.
                local lines = {}
                local keys = {}
                for key, _ in pairs(doc) do
                    if key ~= "configurations" then
                        table.insert(keys, key)
                    end
                end
                table.sort(keys)
                for _, key in ipairs(keys) do
                    table.insert(lines, string.format("    %s: %s,", json.encode(key), json.encode(doc[key])))
                end

                table.insert(lines, "    \"configurations\": [")
                for i, cfg in ipairs(kept) do
                    table.insert(lines, "        " .. json.encode(cfg) .. (i < #kept and "," or ""))
                end
                table.insert(lines, "    ]")

                local launch_content = "{\n" .. table.concat(lines, "\n") .. "\n}\n"

                os.mkdir(launch_dir)
                io.writefile(launch_path, launch_content)
            end
        end)
end

-- ========================================
-- Task: debug - build in debug mode
-- ========================================
-- With several targets defined this configures debug mode and builds all of
-- them. To build a single target use `xmake build <stem>` or the extension.
task("debug")
    set_menu { usage = "xmake debug", description = "Build in debug mode" }
    on_run(function ()
        os.exec("xmake f -m debug -y")
        os.exec("xmake")
    end)
    task_end()

-- ========================================
-- Task: release - build in release mode
-- ========================================
task("release")
    set_menu { usage = "xmake release", description = "Build in release mode" }
    on_run(function ()
        os.exec("xmake f -m release -y")
        os.exec("xmake")
    end)
    task_end()
