-- ============================================
-- xmake.lua template for STM32
-- Generated by Xmake Tools extension
-- ============================================

set_config("plat", "cross")
set_config("arch", "arm")

includes(".lua/tasks/*.lua")

-- ========================================
-- Optimization presets configuration
-- Based on GCC optimization levels
-- ========================================
local optimization_presets = {
    ["debug"] = {
        opt_flag = "-O0", debug_level = 3, lto = false,
        description = "No optimization, full debug info"
    },
    ["debug-optimized"] = {
        opt_flag = "-Og", debug_level = 3, lto = false,
        description = "Optimized for debugging"
    },
    ["balanced"] = {
        opt_flag = "-O1", debug_level = 2, lto = false,
        description = "Basic optimization"
    },
    ["release"] = {
        opt_flag = "-Os", debug_level = 1, lto = false,
        description = "Optimized for size"
    },
    ["speed"] = {
        opt_flag = "-O2", debug_level = 1, lto = false,
        description = "Optimized for speed"
    },
    ["speed-max"] = {
        opt_flag = "-O3", debug_level = 0, lto = false,
        description = "Maximum speed optimization"
    },
    ["size-max"] = {
        opt_flag = "-Oz", debug_level = 0, lto = false,
        description = "Maximum size optimization"
    },
    ["release-lto"] = {
        opt_flag = "-Os", debug_level = 1, lto = true,
        description = "Size optimization with LTO"
    }
}

-- ========================================
-- Get optimization flags for current mode
-- ========================================
local function get_optimization_flags(target)
    local mode = get_config("mode") or "debug"

    local optimization = target:data("optimization") or {}

    local preset_id = optimization[mode] or mode
    local preset = optimization_presets[preset_id] or optimization_presets["debug"]

    local opt_flag   = preset.opt_flag
    local debug_flag = "-g" .. tostring(preset.debug_level)
    local lto_flag   = preset.lto and "-flto" or nil

    return opt_flag, debug_flag, lto_flag
end

-- ========================================
-- Toolchain
-- ========================================
toolchain("stm32-gcc")
    on_load(function (toolchain)
        import("core.base.json")

        toolchain:set("kind", "standalone")
        toolchain:set("sdkdir", json.decode(io.readfile(".lua/config.json")).arm_gcc_path)
        toolchain:set("toolset", "cc", "arm-none-eabi-gcc")
        toolchain:set("toolset", "cxx", "arm-none-eabi-g++")
        toolchain:set("toolset", "ld", "arm-none-eabi-g++")
        toolchain:set("toolset", "as", "arm-none-eabi-gcc")
        toolchain:set("toolset", "ar", "arm-none-eabi-ar")
        toolchain:set("toolset", "objcopy", "arm-none-eabi-objcopy")
        toolchain:set("toolset", "size", "arm-none-eabi-size")
    end)

    on_check(function (toolchain)
        return true
    end)
toolchain_end()

-- ========================================
-- Build modes
-- ========================================
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})

-- ========================================
-- Main target
-- ========================================
target("firmware")
    set_kind("binary")

    -- ========================================
    -- Loading the structure
    -- ========================================
    on_load(function (target)
        import("core.base.json")

        local config_path = ".lua/config.json"
        if not os.isfile(config_path) then
            raise(".lua/config.json not found!")
        end

        local settings = json.decode(io.readfile(config_path))

        target:set("name",       settings.name)
        target:set("languages",  "c17", "c++20")
        target:set("filename",   settings.name .. ".elf")
        target:set("toolchains", "stm32-gcc")
        target:set("warnings",   "all", "extra", "pedantic", "error=return-type")

        target:data_set("project_name", settings.name)
        target:data_set("mcu_series",   settings.mcu_series)
        target:data_set("mcu_core",     settings.mcu_core)
        target:data_set("mcu_device",   settings.mcu_device)
        target:data_set("ld_script",    settings.ld_script)
        target:data_set("svd_file",     settings.svd_file)
        target:data_set("jlink_path",   settings.jlink_path)
        target:data_set("optimization", settings.optimization)
        target:data_set("postbuild",    settings.postbuild or nil)

        if settings.clang_format then
            local format_content = "# Generated automatically by Xmake from .lua/config.json\n\r---\n"
            for key, val in pairs(settings.clang_format) do
                if type(val) == "string" then
                    format_content = format_content .. string.format("%s: '%s'\n", key, val)
                else
                    format_content = format_content .. string.format("%s: %s\n", key, tostring(val))
                end
            end

            io.writefile("./build/.clang-format", format_content, {check = true})

            vscode_settings = table.concat({
                "{",
                "    \"editor.formatOnSave\": true,",
                "    \"[c]\": {",
                "        \"editor.defaultFormatter\": \"ms-vscode.cpptools\",",
                "        \"editor.formatOnSave\": true",
                "    },",
                "    \"[cpp]\": {",
                "        \"editor.defaultFormatter\": \"ms-vscode.cpptools\",",
                "        \"editor.formatOnSave\": true",
                "    }",
                "}"
            }, "\n")
            os.mkdir(".vscode")
            io.writefile(".vscode/settings.json", vscode_settings, {check = true})
        end

        if settings.defines then
            for _, def in ipairs(settings.defines) do
                target:add("defines", settings.mcu_series, def)
            end
        end

        if settings.includedirs then
            for _, dir in ipairs(settings.includedirs) do
                target:add("includedirs", dir)
            end
        end

        if settings.sources then
            for _, file in ipairs(settings.sources) do
                target:add("files", file)
            end
        end
    end)

    -- ========================================
    -- Compiler Configuration
    -- ========================================
    on_config(function (target)
        -- MCU flags
        local mcpu_flags = "-mcpu=".. target:data("mcu_core") .." -mthumb"
        local fpu_flags  = {"-mfpu=fpv4-sp-d16", "-mfloat-abi=hard"}

        target:add("cxflags", mcpu_flags, fpu_flags, {force = true})
        target:add("asflags", mcpu_flags, fpu_flags, {force = true})
        target:add("ldflags", mcpu_flags, fpu_flags, {force = true})

        -- Optimisation (dynamic based on presets)
        local opt_flag, debug_flag, lto_flag = get_optimization_flags(target)
        target:add("cxflags", opt_flag, debug_flag, "-gdwarf-2")

        -- LTO support
        if lto_flag then
            target:add("cxflags", lto_flag)
            target:add("ldflags", lto_flag)
        end

        -- ========================================
        -- Compilation flags
        -- ========================================
        target:add("cxflags", "-Wall", "-Wextra", "-Werror=return-type")
        target:add("cxflags", "-ffunction-sections", "-fdata-sections")
        target:add("cxxflags", "-fno-exceptions", "-fno-rtti")

        -- ========================================
        -- Linker flags
        -- ========================================
        target:add("ldflags", "-T" .. target:data("ld_script"), {force = true})
        target:add("ldflags", "-specs=nano.specs", "-specs=nosys.specs", {force = true})
        target:add("ldflags", "-Wl,--gc-sections")

        local map_path = target:data("project_name") .. ".map"
        target:add("ldflags", "-Wl,-Map=" .. map_path, {force = true})
    end)

    -- ========================================
    -- Post-build: bin/hex + size + launch.json
    -- ========================================
    after_build(function (target)
        local targetfile = path.normalize(target:targetfile())
        local outdir     = path.normalize(path.directory(targetfile))
        local basename   = path.basename(targetfile)

        cprint("\r\n${rocket} ${green}Generating binary files${clear}")
        os.exec('arm-none-eabi-objcopy -O binary "%s" "%s/%s.bin"', targetfile, outdir, basename)   -- .bin
        os.exec('arm-none-eabi-objcopy -O ihex "%s" "%s/%s.hex"', targetfile, outdir, basename)     -- .hex
        os.exec('arm-none-eabi-size "%s"', targetfile)                                              -- size

        -- Post-build:
        if target:data("postbuild") then
            cprint("\r\n${gear} ${green}Postbuild run:${clear}")
            os.exec(target:data("postbuild"))
        end

        -- Generate launch.json for Cortex Debug
        cprint("\r\n${hammer} ${green}Generating ${cyan}.vscode/launch.json${clear}")
        local jlink_gdb = path.normalize(target:data("jlink_path")):gsub("[Jj][Ll][Ii][Nn][Kk]%.exe", "JLinkGDBServerCL.exe")
        if jlink_gdb == path.normalize(target:data("jlink_path")) then
            jlink_gdb = "JLinkGDBServerCL.exe"
        end

        local relative_elf_path = path.relative(targetfile, os.projectdir()):gsub("\\", "/")
        local jlink_gdb_norm    = jlink_gdb:gsub("\\", "/")
        local svd_file_norm     = (target:data("svd_file") or ""):gsub("\\", "/")

        local launch_config = table.concat({
            "{",
            "    \"version\": \"0.2.0\",",
            "    \"configurations\": [",
            "        {",
            "            \"name\": \"JLink Debug\",",
            "            \"cwd\": \"${workspaceFolder}\",",
            "            \"executable\": \"${workspaceFolder}/%s\",",
            "            \"request\": \"launch\",",
            "            \"type\": \"cortex-debug\",",
            "            \"servertype\": \"jlink\",",
            "            \"serverpath\": \"%s\",",
            "            \"device\": \"%s\",",
            "            \"interface\": \"swd\",",
            "            \"svdFile\": \"${workspaceFolder}/%s\",",
            "            \"runToEntryPoint\": \"main\",",
            "            \"showDevDebugOutput\": \"raw\"",
            "        }",
            "    ]",
            "}"
        }, "\n")

        os.mkdir(".vscode")
        io.writefile(".vscode/launch.json", launch_config:format(relative_elf_path, jlink_gdb_norm, target:data("mcu_device"), svd_file_norm))
    end)

-- ========================================
-- Task: debug - build in debug mode
-- ========================================
task("debug")
    set_menu { usage = "xmake debug", description = "Build in debug mode" }
    on_run(function ()
        os.exec("xmake f -m debug -y")
        os.exec("xmake")
    end)

-- ========================================
-- Task: release - build in release mode
-- ========================================
task("release")
    set_menu { usage = "xmake release", description = "Build in release mode" }
    on_run(function ()
        os.exec("xmake f -m release -y")
        os.exec("xmake")
    end)
